### ISSUE TITLE
When posting a job, cannot upload picture using firefox

### ISSUE THREAD

**Issue by devansingaram** [devansingaram/tribehired#160]
@drewbdennis can you look into this? 

When I click upload picture in chrome, it works, but when try using firefox, the windows explorer does not load.

Please check it.

**Comment by devansingaram** [comment]
ok, have reverted the previous javascript on the live server, uploads are fine on firefox now, but wrong cursor shown, which is a lesser issue

**Comment by drewbdennis** [comment]
Fixed on tribehiredmail.com... please test...

**Comment by devansingaram** [comment]
A request from a hirer, to be able to click on the image to pop up the fileuploader. 

Would be great to get this in

**Comment by ykgoon** [comment]
Last I check yesterday, this issue still persist in Staging. Anyone need my hands here?
